#!/usr/bin/sh

#    /$$
#   | $$
#   | $$$$$$$   /$$$$$$$  /$$$$$$  /$$  /$$  /$$ /$$$$$$/$$$$
#   | $$__  $$ /$$_____/ /$$__  $$| $$ | $$ | $$| $$_  $$_  $$
#   | $$  \ $$|  $$$$$$ | $$  \ $$| $$ | $$ | $$| $$ \ $$ \ $$
#   | $$  | $$ \____  $$| $$  | $$| $$ | $$ | $$| $$ | $$ | $$
#   | $$$$$$$/ /$$$$$$$/| $$$$$$$/|  $$$$$/$$$$/| $$ | $$ | $$
#   |_______/ |_______/ | $$____/  \_____/\___/ |__/ |__/ |__/
#                       | $$
#  		        					| $$
#                       |__/

SCREEN1="eDP1"
SCREEN2="HDMI1"

display=`xrandr | grep HDMI1 | awk '{print $2}'`

if [ "$display" == "connected" ] ; then #Double screen; exported from `arandr`
	xrandr --output eDP1 --primary --mode 1920x1080 --pos 1920x0 --rotate normal --output DP1 --off --output HDMI1 --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI2 --off --output VIRTUAL1 --off
	bspc monitor HDMI1 -d 1 2 3 4 5
	bspc monitor eDP1 -d 6 7 8 9 0
	sh $HOME/.config/polybar/launch.sh 2 #run dual screen bars
else #Single screen; exported from `arandr`
	xrandr --output eDP1 --primary --mode 1920x1080 --pos 1920x0 --rotate normal --output HDMI1 --off --output DP1 --off --output HDMI2 --off
	bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 0
	sh $HOME/.config/polybar/launch.sh #run bar
fi

###Autostart
sxhkd &
compton &
bluetoothctl power on &
feh --bg-scale $HOME/Pictures/wallpaper.png

###Config
bspc config border_width       5
bspc config window_gap         7
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
